# Bike Share Capstone Project

## Section 1: Import Data

In [25]:
# Load Packages
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
import prettyplotlib as ppl
import calendar

from datetime import datetime, timedelta, date

sns.set_style('whitegrid')

%matplotlib inline
%config InlineBackend.figure_format = 'retina'

##### Import and Load Data

In [84]:
# Load CitiBike Data from Desktop folder
# Original CitiBike dataset from: https://www.citibikenyc.com/system-data
citibike_file_list = os.listdir('/Users/Snyder/Desktop/DSI-SF-Capstone-Datasets/citibike-tripdata-201307-201605/')
#citibike_file_list = os.listdir('/Volumes/Snyder_Mobile_HD/DSI-SF-Capstone-Datasets/citibike-tripdata-201307-201605/')
citibike_file_list

['201307-citibike-tripdata.csv',
 '201308-citibike-tripdata.csv',
 '201309-citibike-tripdata.csv',
 '201310-citibike-tripdata.csv',
 '201311-citibike-tripdata.csv',
 '201312-citibike-tripdata.csv',
 '201401-citibike-tripdata.csv',
 '201402-citibike-tripdata.csv',
 '201403-citibike-tripdata.csv',
 '201404-citibike-tripdata.csv',
 '201405-citibike-tripdata.csv',
 '201406-citibike-tripdata.csv',
 '201407-citibike-tripdata.csv',
 '201408-citibike-tripdata.csv',
 '201409-citibike-tripdata.csv',
 '201410-citibike-tripdata.csv',
 '201411-citibike-tripdata.csv',
 '201412-citibike-tripdata.csv',
 '201502-citibike-tripdata.csv',
 '201503-citibike-tripdata.csv',
 '201504-citibike-tripdata.csv',
 '201505-citibike-tripdata.csv',
 '201506-citibike-tripdata.csv',
 '201507-citibike-tripdata.csv',
 '201508-citibike-tripdata.csv',
 '201509-citibike-tripdata.csv',
 '201510-citibike-tripdata.csv',
 '201511-citibike-tripdata.csv',
 '201604-citibike-tripdata.csv',
 '201605-citibike-tripdata.csv']

In [70]:
#Create citibike df 
#citibike_dfs = [pd.read_csv('/Users/Snyder/Desktop/DSI-SF-Capstone-Datasets/citibike-tripdata-201307-201605/' + file) for file in citibike_file_list]
#citibike_dfs = [pd.read_csv('/Volumes/Snyder_Mobile_HD/DSI-SF-Capstone-Datasets/citibike-tripdata-201307-201605/' + file) for file in citibike_file_list]
#citibike = pd.concat(citibike_dfs)

In [71]:
citibike.head(3)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,634,2013-07-01 00:00:00,2013-07-01 00:10:34,164,E 47 St & 2 Ave,40.753231,-73.970325,504,1 Ave & E 15 St,40.732219,-73.981656,16950,Customer,\N,0
1,1547,2013-07-01 00:00:02,2013-07-01 00:25:49,388,W 26 St & 10 Ave,40.749718,-74.002950,459,W 20 St & 11 Ave,40.746745,-74.007756,19816,Customer,\N,0
2,178,2013-07-01 00:01:04,2013-07-01 00:04:02,293,Lafayette St & E 8 St,40.730287,-73.990765,237,E 11 St & 2 Ave,40.730473,-73.986724,14548,Subscriber,1980,2

In [72]:
for col in citibike.columns:
    print col

tripduration
starttime
stoptime
start station id
start station name
start station latitude
start station longitude
end station id
end station name
end station latitude
end station longitude
bikeid
usertype
birth year
gender

In [73]:
# Replace space in columnns titles with underscores
citibike.columns = citibike.columns.map(lambda x: x.replace(' ', '_'))

for col in citibike.columns:
    print col

tripduration
starttime
stoptime
start_station_id
start_station_name
start_station_latitude
start_station_longitude
end_station_id
end_station_name
end_station_latitude
end_station_longitude
bikeid
usertype
birth_year
gender

In [75]:
citibike.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 24192122 entries, 0 to 1212279
Data columns (total 15 columns):
tripduration               int64
starttime                  object
stoptime                   object
start_station_id           int64
start_station_name         object
start_station_latitude     float64
start_station_longitude    float64
end_station_id             int64
end_station_name           object
end_station_latitude       float64
end_station_longitude      float64
bikeid                     int64
usertype                   object
birth_year                 object
gender                     int64
dtypes: float64(4), int64(5), object(6)
memory usage: 2.9+ GB

In [78]:
# Convert to datetime
# citibike.starttime = pd.to_datetime(citibike.starttime)
# citibike.stoptime = pd.to_datetime(citibike.stoptime)

In [27]:
# PS: The to_datetime cell took 4+ hours to run

In [28]:
citibike.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 24192122 entries, 0 to 1212279
Data columns (total 15 columns):
tripduration               int64
starttime                  datetime64[ns]
stoptime                   datetime64[ns]
start_station_id           int64
start_station_name         object
start_station_latitude     float64
start_station_longitude    float64
end_station_id             int64
end_station_name           object
end_station_latitude       float64
end_station_longitude      float64
bikeid                     int64
usertype                   object
birth_year                 object
gender                     int64
dtypes: datetime64[ns](2), float64(4), int64(5), object(4)
memory usage: 2.9+ GB

In [86]:
print len(citibike.start_station_id.unique())
print len(citibike.end_station_id.unique())

498
514

In [59]:
# Create DF of uniqe stations

#stations = citibike
#stations.columns


# stations = stations.drop(['tripduration', 'starttime', 'stoptime', 'end_station_id', u'end_station_name',
#        'end_station_latitude', 'end_station_longitude', 'bikeid', 'usertype', 'birth_year', 'gender'], axis = 1, inplace = True)

# Remove duplicates
#stations = stations.drop_duplicates('start_station_name')
#len(stations.start_station_id.unique())

# stations.columns = stations.columns.map(lambda x: x.replace('start_', ''))
# stations.columns

Index([u'station_id', u'station_name', u'station_latitude',
       u'station_longitude'],
      dtype='object')

In [82]:
#stations.to_csv('citibike_stations.csv', index = False)
stations = pd.read_csv('/Users/Snyder/Desktop/DSI-SF-1-SNYDER827/Projects/Capstone/citibike_stations.csv')
stations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 4 columns):
station_id           503 non-null int64
station_name         503 non-null object
station_latitude     503 non-null float64
station_longitude    503 non-null float64
dtypes: float64(2), int64(1), object(1)
memory usage: 15.8+ KB

In [79]:
citibike.head()

,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,634,2013-07-01 00:00:00,2013-07-01 00:10:34,164,E 47 St & 2 Ave,40.753231,-73.970325,504,1 Ave & E 15 St,40.732219,-73.981656,16950,Customer,\N,0
1,1547,2013-07-01 00:00:02,2013-07-01 00:25:49,388,W 26 St & 10 Ave,40.749718,-74.002950,459,W 20 St & 11 Ave,40.746745,-74.007756,19816,Customer,\N,0
2,178,2013-07-01 00:01:04,2013-07-01 00:04:02,293,Lafayette St & E 8 St,40.730287,-73.990765,237,E 11 St & 2 Ave,40.730473,-73.986724,14548,Subscriber,1980,2
3,1580,2013-07-01 00:01:06,2013-07-01 00:27:26,531,Forsyth St & Broome St,40.718939,-73.992663,499,Broadway & W 60 St,40.769155,-73.981918,16063,Customer,\N,0
4,757,2013-07-01 00:01:10,2013-07-01 00:13:47,382,University Pl & E 14 St,40.734927,-73.992005,410,Suffolk St & Stanton St,40.720664,-73.985180,19213,Subscriber,1986,1

In [81]:
citibike[citibike['start_station_name'] == 'Fulton St & Broadway']

,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
651516,1821,2015-08-17 18:18:05,2015-08-17 18:48:26,319,Fulton St & Broadway,40.711066,-74.009447,521,8 Ave & W 31 St,40.750967,-73.994442,23406,Subscriber,1989,2
651521,466,2015-08-17 18:40:28,2015-08-17 18:48:15,319,Fulton St & Broadway,40.711066,-74.009447,348,W Broadway & Spring St,40.724910,-74.001547,22459,Subscriber,1985,1
651528,1806,2015-08-17 18:42:53,2015-08-17 19:13:00,319,Fulton St & Broadway,40.711066,-74.009447,536,1 Ave & E 30 St,40.741444,-73.975361,23708,Subscriber,1990,2
651533,1553,2015-08-17 19:41:24,2015-08-17 20:07:17,319,Fulton St & Broadway,40.711066,-74.009447,530,11 Ave & W 59 St,40.771522,-73.990541,23753,Subscriber,1987,1
651538,2308,2015-08-17 20:56:09,2015-08-17 21:34:37,319,Fulton St & Broadway,40.711066,-74.009447,352,W 56 St & 6 Ave,40.763406,-73.977225,22344,Subscriber,1989,2
651543,1031,2015-08-17 22:07:03,2015-08-17 22:24:15,319,Fulton St & Broadway,40.711066,-74.009447,334,W 20 St & 7 Ave,40.742388,-73.997262,16132,Subscriber,1988,1
655980,612,2015-08-18 14:52:31,2015-08-18 15:02:43,319,Fulton St & Broadway,40.711066,-74.009447,268,Howard St & Centre St,40.719105,-73.999733,22274,Subscriber,1959,1
656654,197,2015-08-18 15:16:40,2015-08-18 15:19:57,319,Fulton St & Broadway,40.711066,-74.009447,264,Maiden Ln & Pearl St,40.707065,-74.007319,20055,Subscriber,1976,1
657502,360,2015-08-18 15:45:19,2015-08-18 15:51:19,319,Fulton St & Broadway,40.711066,-74.009447,82,St James Pl & Pearl St,40.711174,-74.000165,22220,Subscriber,1974,1
657559,1347,2015-08-18 15:47:30,2015-08-18 16:09:57,319,Fulton St & Broadway,40.711066,-74.009447,293,Lafayette St & E 8 St,40.730287,-73.990765,19970,Customer,NaN,0
657562,1354,2015-08-18 15:47:32,2015-08-18 16:10:07,319,Fulton St & Broadway,40.711066,-74.009447,293,Lafayette St & E 8 St,40.730287,-73.990765,21585,Customer,NaN,0
659729,859,2015-08-18 16:46:25,2015-08-18 17:00:44,319,Fulton St & Broadway,40.711066,-74.009447,328,Watts St & Greenwich St,40.724055,-74.009660,17720,Subscriber,1983,2
660225,406,2015-08-18 16:56:41,2015-08-18 17:03:27,319,Fulton St & Broadway,40.711066,-74.009447,248,Laight St & Hudson St,40.721854,-74.007718,20881,Subscriber,1988,1
661282,922,2015-08-18 17:12:56,2015-08-18 17:28:18,319,Fulton St & Broadway,40.711066,-74.009447,537,Lexington Ave & E 24 St,40.740259,-73.984092,21430,Subscriber,1991,1
661622,620,2015-08-18 17:17:59,2015-08-18 17:28:19,319,Fulton St & Broadway,40.711066,-74.009447,128,MacDougal St & Prince St,40.727103,-74.002971,24348,Subscriber,1986,1
661763,801,2015-08-18 17:19:48,2015-08-18 17:33:10,319,Fulton St & Broadway,40.711066,-74.009447,279,Peck Slip & Front St,40.707873,-74.001670,22021,Customer,NaN,0
662118,1481,2015-08-18 17:24:42,2015-08-18 17:49:24,319,Fulton St & Broadway,40.711066,-74.009447,455,1 Ave & E 44 St,40.750020,-73.969053,23657,Subscriber,1988,1
662341,1527,2015-08-18 17:27:58,2015-08-18 17:53:26,319,Fulton St & Broadway,40.711066,-74.009447,116,W 17 St & 8 Ave,40.741776,-74.001497,19482,Subscriber,1982,1
663362,586,2015-08-18 17:41:35,2015-08-18 17:51:21,319,Fulton St & Broadway,40.711066,-74.009447,475,E 16 St & Irving Pl,40.735243,-73.987586,18954,Subscriber,1975,1
663852,1207,2015-08-18 17:48:22,2015-08-18 18:08:29,319,Fulton St & Broadway,40.711066,-74.009447,508,W 46 St & 11 Ave,40.763414,-73.996674,22181,Subscriber,1991,1
663958,207,2015-08-18 17:49:51,2015-08-18 17:53:18,319,Fulton St & Broadway,40.711066,-74.009447,360,William St & Pine St,40.707179,-74.008873,16156,Subscriber,1989,1
664025,864,2015-08-18 17:50:34,2015-08-18 18:04:59,319,Fulton St & Broadway,40.711066,-74.009447,483,E 12 St & 3 Ave,40.732233,-73.988900,15935,Subscriber,1984,1
664497,2145,2015-08-18 17:56:38,2015-08-18 18:32:23,319,Fulton St & Broadway,40.711066,-74.009447,522,E 51 St & Lexington Ave,40.757148,-73.972078,16889,Customer,NaN,0
664545,2106,2015-08-18 17:57:12,2015-08-18 18:32:18,319,Fulton St & Broadway,40.711066,-74.009447,522,E 51 St & Lexington Ave,40.757148,-73.972078,20261,Customer,NaN,0
666301,686,2015-08-18 18:19:12,2015-08-18 18:30:38,319,Fulton St & Broadway,40.711066,-74.009447,346,Bank St & Hudson St,40.736529,-74.006180,16736,Subscriber,1984,1
666945,1620,2015-08-18 18:27:10,2015-08-18 18:54:10,319,Fulton St & Broadway,40.711066,-74.009447,442,W 27 St & 7 Ave,40.746647,-73.993915,16361,Subscriber,1958,1
667629,701,2015-08-18 18:36:41,2015-08-18 18:48:23,319,Fulton St & Broadway,40.711066,-74.009447,128,MacDougal St & Prince St,40.727103,-74.002971,20003,Customer,NaN,0
667745,803,2015-08-18 18:38:00,2015-08-18 18:51:23,319,Fulton St & Broadway,40.711066,-74.009447,482,W 15 St & 7 Ave,40.739355,-73.999318,20762,Customer,NaN,0
668123,663,2015-08-18 18:42:47,2015-08-18 18:53:51,319,Fulton St & Broadway,40.711066,-74.009447,369,Washington Pl & 6 Ave,40.732241,-74.000264,18465,Subscriber,1990,1
668537,1008,2015-08-18 18:49:14,2015-08-18 19:06:03,319,Fulton St & Broadway,40.711066,-74.009447,358,Christopher St & Greenwich St,40.732916,-74.007114,17598,Subscriber,1964,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1199894,1017,2016-05-31 18:31:28,2016-05-31 18:48:26,319,Fulton St & Broadway,40.711066,-74.009447,345,W 13 St & 6 Ave,40.736494,-73.997044,17594,Subscriber,1977,1
1199940,766,2016-05-31 18:31:56,2016-05-31 18:44:43,319,Fulton St & Broadway,40.711066,-74.009447,348,W Broadway & Spring St,40.724910,-74.001547,19254,Subscriber,1963,1
1200098,514,2016-05-31 18:33:46,2016-05-31 18:42:21,319,Fulton St & Broadway,40.711066,-74.009447,151,Cleveland Pl & Spring St,40.722104,-73.997249,19267,Subscriber,1962,1
1200112,814,2016-05-31 18:33:52,2016-05-31 18:47:26,319,Fulton St & Broadway,40.711066,-74.009447,392,Jay St & Tech Pl,40.695065,-73.987167,17151,Subscriber,1976,1
1200314,616,2016-05-31 18:36:05,2016-05-31 18:46:21,319,Fulton St & Broadway,40.711066,-74.009447,250,Lafayette St & Jersey St,40.724561,-73.995653,21178,Subscriber,1986,1
1200360,201,2016-05-31 18:36:35,2016-05-31 18:39:56,319,Fulton St & Broadway,40.711066,-74.009447,147,Greenwich St & Warren St,40.715422,-74.011220,18107,Subscriber,1977,1
1200910,1235,2016-05-31 18:42:33,2016-05-31 19:03:09,319,Fulton St & Broadway,40.711066,-74.009447,453,W 22 St & 8 Ave,40.744751,-73.999154,14720,Subscriber,1986,1
1201444,821,2016-05-31 18:48:47,2016-05-31 19:02:29,319,Fulton St & Broadway,40.711066,-74.009447,349,Rivington St & Ridge St,40.718502,-73.983299,19659,Subscriber,1990,1
1201592,663,2016-05-31 18:50:41,2016-05-31 19:01:44,319,Fulton St & Broadway,40.711066,-74.009447,295,Pike St & E Broadway,40.714067,-73.992939,19568,Subscriber,1985,1
1201883,512,2016-05-31 18:54:35,2016-05-31 19:03:07,319,Fulton St & Broadway,40.711066,-74.009447,348,W Broadway & Spring St,40.724910,-74.001547,17106,Subscriber,1966,1
1201888,3211,2016-05-31 18:54:40,2016-05-31 19:48:12,319,Fulton St & Broadway,40.711066,-74.009447,454,E 51 St & 1 Ave,40.754557,-73.965930,16505,Customer,NaN,0
1202573,745,2016-05-31 19:04:19,2016-05-31 19:16:45,319,Fulton St & Broadway,40.711066,-74.009447,128,MacDougal St & Prince St,40.727103,-74.002971,18553,Subscriber,1959,2
1202811,901,2016-05-31 19:07:31,2016-05-31 19:22:32,319,Fulton St & Broadway,40.711066,-74.009447,278,Concord St & Bridge St,40.697666,-73.984764,23768,Subscriber,1979,1
1202860,1175,2016-05-31 19:08:17,2016-05-31 19:27:53,319,Fulton St & Broadway,40.711066,-74.009447,411,E 6 St & Avenue D,40.722281,-73.976687,20116,Subscriber,1991,1
1202861,1055,2016-05-31 19:08:17,2016-05-31 19:25:53,319,Fulton St & Broadway,40.711066,-74.009447,458,11 Ave & W 27 St,40.751396,-74.005226,17483,Subscriber,1986,2
1202914,1530,2016-05-31 19:08:57,2016-05-31 19:34:28,319,Fulton St & Broadway,40.711066,-74.009447,366,Clinton Ave & Myrtle Ave,40.693261,-73.968896,17997,Subscriber,1991,2
1203160,1336,2016-05-31 19:11:57,2016-05-31 19:34:14,319,Fulton St & Broadway,40.711066,-74.009447,462,W 22 St & 10 Ave,40.746920,-74.004519,20194,Subscriber,1966,1
1203295,871,2016-05-31 19:13:48,2016-05-31 19:28:19,319,Fulton St & Broadway,40.711066,-74.009447,307,Canal St & Rutgers St,40.714275,-73.989900,18500,Subscriber,1990,2
1203982,1193,2016-05-31 19:24:22,2016-05-31 19:44:16,319,Fulton St & Broadway,40.711066,-74.009447,525,W 34 St & 11 Ave,40.755942,-74.002116,19046,Subscriber,1985,1
1204207,903,2016-05-31 19:27:33,2016-05-31 19:42:36,319,Fulton St & Broadway,40.711066,-74.009447,3224,W 13 St & Hudson St,40.739974,-74.005139,18585,Subscriber,1984,1
1205076,3539,2016-05-31 19:41:31,2016-05-31 20:40:31,319,Fulton St & Broadway,40.711066,-74.009447,319,Fulton St & Broadway,40.711066,-74.009447,18378,Customer,NaN,0
1205165,171,2016-05-31 19:42:56,2016-05-31 19:45:47,319,Fulton St & Broadway,40.711066,-74.009447,264,Maiden Ln & Pearl St,40.707065,-74.007319,24178,Subscriber,1981,1
1205240,1043,2016-05-31 19:44:13,2016-05-31 20:01:36,319,Fulton St & Broadway,40.711066,-74.009447,310,State St & Smith St,40.689269,-73.989129,23820,Subscriber,1978,1
1205581,867,2016-05-31 19:49:30,2016-05-31 20:03:57,319,Fulton St & Broadway,40.711066,-74.009447,250,Lafayette St & Jersey St,40.724561,-73.995653,24744,Subscriber,1964,1
1206318,1264,2016-05-31 20:03:32,2016-05-31 20:24:37,319,Fulton St & Broadway,40.711066,-74.009447,168,W 18 St & 6 Ave,40.739713,-73.994564,17723,Subscriber,1978,2
1208302,2775,2016-05-31 20:46:19,2016-05-31 21:32:35,319,Fulton St & Broadway,40.711066,-74.009447,379,W 31 St & 7 Ave,40.749156,-73.991600,18378,Subscriber,1985,1
1208795,565,2016-05-31 20:58:50,2016-05-31 21:08:15,319,Fulton St & Broadway,40.711066,-74.009447,358,Christopher St & Greenwich St,40.732916,-74.007114,25399,Subscriber,1978,2
1210367,284,2016-05-31 21:55:05,2016-05-31 21:59:49,319,Fulton St & Broadway,40.711066,-74.009447,327,Vesey Pl & River Terrace,40.715338,-74.016584,22313,Subscriber,1993,1
1210509,589,2016-05-31 22:01:36,2016-05-31 22:11:26,319,Fulton St & Broadway,40.711066,-74.009447,161,LaGuardia Pl & W 3 St,40.729170,-73.998102,16386,Subscriber,1986,1
1211981,1237,2016-05-31 23:29:46,2016-05-31 23:50:24,319,Fulton St & Broadway,40.711066,-74.009447,353,S Portland Ave & Hanson Pl,40.685396,-73.974315,24826,Subscriber,1991,1